### ISSUE TITLE
i am unable to book

### ISSUE THREAD

**Issue by nyousefzai** [chingu-voyage3/bears-06#87]
<img width="1619" alt="screen shot 2018-03-05 at 7 25 34 pm" src="https://user-images.githubusercontent.com/27225894/37012761-1b7826fe-20ab-11e8-8b31-18db45c0cc09.png">

**Comment by stephanpssantos** [comment]
It's very difficult to diagnose this when we don't have the context. Based on your previous issues I think you've been altering the original code, so I can't just look at my copy. If you're looking through this for educational purposes or so you can add functionality and contribute, then link us to the repository you're working on and someone might take a look. Otherwise, I don't think anyone here is interested in helping you make your project work.
